### ISSUE TITLE
Command injection inside the ping command

### ISSUE THREAD

**Issue by guillaumemichel** [Zyfarok/softsec-grass#1]
';' is not among the forbidden characters of the parameter of the `ping` command before the call to `popen`, thus it is possible to execute arbitrary command after adding a ';' to the parameter of the `ping` command.
Location: server.cpp, line 172 (ping command), server.cpp, line 58 (popen)

Here is the input to give to the client to open a calculator
```
>>> ping ;xcalc;
```

**Comment by mikanikos** [comment]
Fix ping
