### ISSUE TITLE
Vulnerability in ping command

### ISSUE THREAD

**Issue by qbouvet** [Zyfarok/softsec-grass#17]
Here, void ’run command(const char *command, const int sock)’ in server.cpp:48 is vulnerable. User
input is never sanitized : any input passed to this function is directly passed to ’popen()’. User input is not sanitized in functions such as ’do ping()’ in server.cpp:172, so after logging in, we can send the input ’ping google.com;galculator’ to run a command injection.

**Comment by dathieu** [comment]
Duplicate of #1

**Comment by Zyfarok** [comment]
Close duplicate
